# Generated by Django 4.0.5 on 2022-06-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the breed (e.g. Labrador)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the pet', max_length=100)),
                ('photo_url', models.ImageField(upload_to='images')),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('breed', models.ManyToManyField(help_text='Select the breed of the pet', to='pet_app.breed')),
            ],
        ),
    ]
