# Generated by Django 4.0.5 on 2022-06-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.AddField(
            model_name='pet',
            name='born',
            field=models.DateField(help_text='Enter the date of birth', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='favorite_snack',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
