# Generated by Django 4.0.5 on 2022-06-24 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0003_gender_remove_pet_gender_pet_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='breed',
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet_app.breed'),
        ),
        migrations.RemoveField(
            model_name='pet',
            name='gender',
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet_app.gender'),
        ),
    ]
